name: dotnet package

on: [push]

jobs:
  build-test-push:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK 2.1.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: "2.1.x"
    - name: setup msbuild
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Install dependencies
      run: dotnet restore src/DeepEqual.sln
    - name: Build
      run: dotnet build src/DeepEqual.sln -c Release --no-restore
    - name: Test
      run: dotnet test src/DeepEqual.sln --no-restore
    - name: Pack
      run: dotnet pack src/DeepEqual/DeepEqual.csproj -c Release -o ../.. --no-restore --verbosity normal
    - name: Push
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
